/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcmap;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.GridLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author WRIM
 */
public class Bounds extends javax.swing.JPanel {

    boolean checkBounds = false;
    int unit = 1;
    int Ymin, Ymax;
    long Xmin = 0, Xmax = 0, Zmin = 0, Zmax = 0;
    
    /**
     * Creates new form bounds
     */
    private static void display() {
        String[] items = {"One", "Two", "Three", "Four", "Five"};
        JComboBox combo = new JComboBox(items);
        JTextField field1 = new JTextField("1234.56");
        JTextField field2 = new JTextField("9876.54");
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(combo);
        panel.add(new JLabel("Field 1:"));
        panel.add(field1);
        panel.add(new JLabel("Field 2:"));
        panel.add(field2);
        int result = JOptionPane.showConfirmDialog(null, panel, "Test",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(combo.getSelectedItem()
                + " " + field1.getText()
                + " " + field2.getText());
        } else {
            System.out.println("Cancelled");
        }
    }

    public void run()
    {
        display();
    }
    
    public Bounds()
    {
        this(false, new int[] {0,0,0,0,255,0,0});
    }
    
    public Bounds(boolean check, int[] vals)
    {
        checkBounds = check;
        int i = 0;
        Xmin = vals[i++];
        Ymin = vals[i++];
        Zmin = vals[i++];
        Xmax = vals[i++];
        Ymax = vals[i++];
        Zmax = vals[i++];
        unit = vals[i++];
        
        initComponents();
        if (checkBounds)
        {
            checkBoxAreaToRender.setSelected(true);
            checkCheckbox();
        }
        coordinateYmin.setValue(Ymin);
        coordinateYmax.setValue(Ymax);
        
        //TODO check what's limits?
        int times = 1, step = 1;
        switch(unit)
        {
            case 0:
                times = 512;
                step = 16;
                break;
            case 1:
                times = 32;
                step = 1;
                break;
            case 2:
                times = 1;
                step = 1;
                break;
        }
        coordinateXmin.setModel(new SpinnerNumberModel(Xmin*times/32, Long.MIN_VALUE, Long.MAX_VALUE, step));
        coordinateXmax.setModel(new SpinnerNumberModel(Xmax*times/32, Long.MIN_VALUE, Long.MAX_VALUE, step));
        coordinateZmin.setModel(new SpinnerNumberModel(Zmin*times/32, Long.MIN_VALUE, Long.MAX_VALUE, step));
        coordinateZmax.setModel(new SpinnerNumberModel(Zmax*times/32, Long.MIN_VALUE, Long.MAX_VALUE, step));
        JRadioButton[] radio = new JRadioButton[] {radioBlocks, radioChunks, radioFiles};
        radioUnit.setSelected(radio[unit].getModel(), true);
    }
        
    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                //display();
            }
        });
        
        //System.out.println("sss");
        Bounds panel = new Bounds();
        //panel.setVisible(true);
        //JOptionPane.showConfirmDialog(null, panel, "Test",
        //    JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        JOptionPane.showMessageDialog(null, panel, "Test",
            JOptionPane.PLAIN_MESSAGE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioUnit = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        checkBoxAreaToRender = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        coordinateYmin = new javax.swing.JSpinner();
        coordinateYmax = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        labelX = new javax.swing.JLabel();
        labelZ = new javax.swing.JLabel();
        coordinateXmin = new javax.swing.JSpinner();
        coordinateXmax = new javax.swing.JSpinner();
        labelToX = new javax.swing.JLabel();
        labelFromX = new javax.swing.JLabel();
        coordinateZmin = new javax.swing.JSpinner();
        coordinateZmax = new javax.swing.JSpinner();
        labelToZ = new javax.swing.JLabel();
        labelFromZ = new javax.swing.JLabel();
        radioBlocks = new javax.swing.JRadioButton();
        radioChunks = new javax.swing.JRadioButton();
        radioFiles = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        checkBoxAreaToRender.setText("Area to render:");
        checkBoxAreaToRender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAreaToRenderActionPerformed(evt);
            }
        });

        jLabel1.setText("Render heights");

        jLabel2.setText("From:");

        coordinateYmin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        coordinateYmin.setNextFocusableComponent(coordinateYmax);
        coordinateYmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                coordinateYminStateChanged(evt);
            }
        });

        coordinateYmax.setModel(new javax.swing.SpinnerNumberModel(255, 0, 255, 1));
        coordinateYmax.setToolTipText("");
        coordinateYmax.setName(""); // NOI18N
        coordinateYmax.setNextFocusableComponent(coordinateYmin);
        coordinateYmax.setRequestFocusEnabled(false);
        coordinateYmax.setValue(255);
        coordinateYmax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                coordinateYmaxStateChanged(evt);
            }
        });

        jLabel3.setText("To:");

        jCheckBox2.setText("Increase scaling");

        labelX.setText("Axis X");
        labelX.setEnabled(false);

        labelZ.setText("Axis Z");
        labelZ.setEnabled(false);

        coordinateXmin.setEnabled(false);
        coordinateXmin.setValue(-512);
        coordinateXmin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                coordinateXminStateChanged(evt);
            }
        });

        coordinateXmax.setToolTipText("");
        coordinateXmax.setEnabled(false);
        coordinateXmax.setName(""); // NOI18N
        coordinateXmax.setRequestFocusEnabled(false);
        coordinateXmax.setValue(511);

        labelToX.setText("To:");
        labelToX.setEnabled(false);

        labelFromX.setText("From:");
        labelFromX.setEnabled(false);

        coordinateZmin.setEnabled(false);
        coordinateZmin.setValue(-512);

        coordinateZmax.setToolTipText("");
        coordinateZmax.setEnabled(false);
        coordinateZmax.setName(""); // NOI18N
        coordinateZmax.setRequestFocusEnabled(false);
        coordinateZmax.setValue(511);

        labelToZ.setText("To:");
        labelToZ.setEnabled(false);

        labelFromZ.setText("From:");
        labelFromZ.setEnabled(false);

        radioUnit.add(radioBlocks);
        radioBlocks.setSelected(true);
        radioBlocks.setText("Blocks");
        radioBlocks.setEnabled(false);

        radioUnit.add(radioChunks);
        radioChunks.setText("Chunks");
        radioChunks.setEnabled(false);

        radioUnit.add(radioFiles);
        radioFiles.setText(".mcr/.mca files");
        radioFiles.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxAreaToRender)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelX, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelFromX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelToX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coordinateXmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coordinateXmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(labelZ, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelFromZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelToZ, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coordinateZmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coordinateZmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioChunks, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coordinateYmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coordinateYmax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxAreaToRender)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coordinateYmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coordinateYmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coordinateXmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFromX))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coordinateXmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelToX)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelZ)
                                .addComponent(labelX))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coordinateZmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFromZ))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coordinateZmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelToZ))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioBlocks)
                            .addComponent(radioChunks)
                            .addComponent(radioFiles)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void coordinateYminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_coordinateYminStateChanged
        if (Integer.parseInt(coordinateYmax.getValue().toString()) < 
                Integer.parseInt(coordinateYmin.getValue().toString()))
        {
            coordinateYmax.setValue(coordinateYmin.getValue());
        }
    }//GEN-LAST:event_coordinateYminStateChanged

    private void coordinateYmaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_coordinateYmaxStateChanged
        if (Integer.parseInt(coordinateYmax.getValue().toString()) < 
                Integer.parseInt(coordinateYmin.getValue().toString()))
        {
            coordinateYmin.setValue(coordinateYmax.getValue());
        }
    }//GEN-LAST:event_coordinateYmaxStateChanged

    private void checkBoxAreaToRenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAreaToRenderActionPerformed
        checkCheckbox();
    }//GEN-LAST:event_checkBoxAreaToRenderActionPerformed

    private void coordinateXminStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_coordinateXminStateChanged
        System.out.println(coordinateXmin.getValue());
    }//GEN-LAST:event_coordinateXminStateChanged

    private void checkCheckbox()
    {
        boolean value = checkBoxAreaToRender.isSelected();
        Component cm[] = {labelFromX, labelFromZ, labelToX, labelToZ, labelX, labelZ, 
            radioBlocks, radioChunks, radioFiles, 
            coordinateXmax, coordinateXmin, coordinateZmax, coordinateZmin};
        for (Component c: cm) {
            c.setEnabled(value);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxAreaToRender;
    private javax.swing.JSpinner coordinateXmax;
    private javax.swing.JSpinner coordinateXmin;
    private javax.swing.JSpinner coordinateYmax;
    private javax.swing.JSpinner coordinateYmin;
    private javax.swing.JSpinner coordinateZmax;
    private javax.swing.JSpinner coordinateZmin;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelFromX;
    private javax.swing.JLabel labelFromZ;
    private javax.swing.JLabel labelToX;
    private javax.swing.JLabel labelToZ;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelZ;
    private javax.swing.JRadioButton radioBlocks;
    private javax.swing.JRadioButton radioChunks;
    private javax.swing.JRadioButton radioFiles;
    private javax.swing.ButtonGroup radioUnit;
    // End of variables declaration//GEN-END:variables
}
