/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcmap;

import java.awt.Component;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author WRIM
 */
public class Window extends javax.swing.JFrame {

    //static String lang = "Język polski";
    private String mcmapEXE;
    static Object lang;
    
    //TODO languages
    static
    {
        
    }
    
    /**
     * Creates new form NewJFrame
     */
    public Window() {
        main(new String[]{"Constructor"});
        initComponents();
        
        String[] combomodel = new String[30];
        for (int i = 0; i < 30; ) {
            combomodel[i] = "Item " + ++i;
        }
        
        //TODO read minecraft profiles (minecraft_profiles.json)
        //TODO prevent from crash when folder is empty (NullPointerException)
        
        File appdata = new File(System.getenv("APPDATA")+"\\.minecraft\\saves");
        File[] files = appdata.listFiles();
        int dirs = 0;
        for (File file: files)
        {
            if (file.isDirectory())
            {
                //System.out.println(file.getName());
                dirs++;
            }
        }
        String[] combomodell = new String[dirs];
        int j = 0;
        for (int i = 0; i < files.length; i++) {
            if (files[i].isDirectory())
            combomodell[j++] = files[i].getName();
        }
        
        ComboSelectWorld.setModel(new javax.swing.DefaultComboBoxModel(combomodell));
        ComboSelectWorld.setSelectedItem(null);
        
        //System.out.println(System.getenv());
        //lTitle.setText("<html><img src=file:///D:\\Dropbox\\NetBeansProjects\\mcmap\\East-wyjebmnienazbityryj.png></html>");

        this.setVisible(true);

        //TODO save on close and question if map is not fully renderred
        /*
        addWindowListener(new WindowAdapter() {
  public void windowClosing(WindowEvent e) {
    int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to exit the program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      dispose();
    }
  }
});
        */
        
        if (System.getProperty("os.name").equalsIgnoreCase("linux"))
        {
            new RunMe("./mcmap",this).check();
            mcmapEXE = "./mcmap";
            checkBox64bit.setEnabled(true);
            checkBox64bit.setSelected(false);
            checkBox64bit.setText("use WINE");
        }
        else if (new RunMe("mcmap64.exe",this).check())
        {
            mcmapEXE = "mcmap64.exe";
            checkBox64bit.setEnabled(true);
            checkBox64bit.setSelected(true);
        }
        else
        {
            new RunMe("mcmap.exe",this).check();
            mcmapEXE = "mcmap.exe";
            memVal.setMaximum(1159);
        }
        //TODO and if none is working?

        //Controller.runProcess("c:\\windows\\system32\\calc.exe");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jProgressBar1 = new javax.swing.JProgressBar();
        lTitle = new javax.swing.JLabel();
        memVal = new javax.swing.JSlider();
        ComboSelectWorld = new javax.swing.JComboBox();
        lOutputFilename = new javax.swing.JLabel();
        lSingleplayerSave = new javax.swing.JRadioButton();
        lCustomPath = new javax.swing.JRadioButton();
        SelectedWorldPath = new javax.swing.JTextField();
        consolePanel = new javax.swing.JScrollPane();
        consoleList = new javax.swing.JList();
        OutputFilename = new javax.swing.JTextField();
        generateMapButton = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        otherParameters = new javax.swing.JTextField();
        lOtherParams = new javax.swing.JLabel();
        lMemoryLimit = new javax.swing.JLabel();
        memLabel = new javax.swing.JLabel();
        newWindowButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTopLeftCorner = new javax.swing.JList();
        lTopLeftCorner = new javax.swing.JLabel();
        checkBox64bit = new javax.swing.JCheckBox();
        lRenderWorld = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listRenderWorld = new javax.swing.JList();
        lRenderType = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listRenderType = new javax.swing.JList();
        checkBoxIncludeSkylight = new javax.swing.JCheckBox();
        coordinateXmin = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        coordinateXmax = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mInformation = new javax.swing.JMenu();
        mVersion = new javax.swing.JMenuItem();
        mUpdate = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mLanguage = new javax.swing.JMenu();
        mLangEnglish = new javax.swing.JRadioButtonMenuItem();
        mLangPolish = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mNimbus = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mcmap 2.4.2b (2.4.2d update available)");
        setMinimumSize(new java.awt.Dimension(460, 660));

        lTitle.setText("<html><a style=\"text-decoration:none;cursor:pointer;\" href=\"http://wrim.pl/mcmap/\">Manually Check for updates</a></html>");
        lTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToSite(evt);
            }
        });

        memVal.setMaximum(1400);
        memVal.setMinimum(701);
        memVal.setValue(1081);
        memVal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zmianaLimituPamieci(evt);
            }
        });

        ComboSelectWorld.setSelectedItem(null);
        ComboSelectWorld.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectWorld(evt);
            }
        });

        lOutputFilename.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lOutputFilename.setText("Output filename");

        lSingleplayerSave.setText("Singleplayer Save");

        lCustomPath.setText("Custom path");

        consoleList.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        consolePanel.setViewportView(consoleList);

        generateMapButton.setText("Generate map");
        generateMapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generujSwiat(evt);
            }
        });

        lOtherParams.setText("Other params");

        lMemoryLimit.setText("Memory limit (use carefuly)");

        memLabel.setText("1795 MB");

        newWindowButton.setText("New window");
        newWindowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWindowClick(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listTopLeftCorner.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "East", "South", "West", "North" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listTopLeftCorner.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTopLeftCorner.setSelectedIndex(0);
        listTopLeftCorner.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTopLeftCornerValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listTopLeftCorner);

        lTopLeftCorner.setText("Top-left corner:");

        checkBox64bit.setSelected(true);
        checkBox64bit.setText("64 bit version / use WINE");
        checkBox64bit.setEnabled(false);
        checkBox64bit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeVersion(evt);
            }
        });

        lRenderWorld.setText("Render world:");

        listRenderWorld.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Overworld", "Nether", "End" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listRenderWorld.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listRenderWorld.setSelectedIndex(0);
        listRenderWorld.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRenderWorldValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listRenderWorld);

        lRenderType.setText("Render type:");

        listRenderType.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Day", "Night", "Underground", "Overworld + caves" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listRenderType.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listRenderType.setToolTipText("");
        listRenderType.setSelectedIndex(0);
        listRenderType.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRenderTypeValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listRenderType);

        checkBoxIncludeSkylight.setText("Include skylight");

        coordinateXmin.setText("0");
        coordinateXmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                coordinateXminFocusLost(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(16)));
        jSpinner1.setName(""); // NOI18N

        coordinateXmax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        coordinateXmax.setText("0");
        coordinateXmax.setToolTipText("");
        coordinateXmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                coordinateXmaxcoordinateXminFocusLost(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("or type the path");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Select profile / world");

        jMenuBar1.setToolTipText("");

        mInformation.setText("About");

        mVersion.setText("Version: N/A");
        mVersion.setToolTipText("");
        mVersion.setEnabled(false);
        mInformation.add(mVersion);

        mUpdate.setText("Update to: 2.4.2d");
        mInformation.add(mUpdate);
        mInformation.add(jSeparator1);

        jMenuItem1.setText("Changelog");
        mInformation.add(jMenuItem1);

        jMenuItem2.setText("License");
        mInformation.add(jMenuItem2);

        jMenuBar1.add(mInformation);

        mLanguage.setText("Language");

        mLangEnglish.setSelected(true);
        mLangEnglish.setText("English (default)");
        mLangEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLanguageEnglish(evt);
            }
        });
        mLanguage.add(mLangEnglish);

        mLangPolish.setText("Polski (polish)");
        mLangPolish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLanguagePolish(evt);
            }
        });
        mLanguage.add(mLangPolish);

        jMenuBar1.add(mLanguage);

        jMenu2.setText("Advanced");

        jMenuItem3.setText("Preview parameters");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Dump colors -> colors dumped as colors.txt");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Load colors (colors-set1.txt)");
        jMenu2.add(jMenuItem5);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Load colors (colors-set1.txt)");
        jMenu2.add(jCheckBoxMenuItem2);
        jMenu2.add(jSeparator2);

        jCheckBoxMenuItem1.setText("Force render as nether");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuItem6.setText("Rendering bounds");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jCheckBoxMenuItem3.setText("Increase y scalling");
        jMenu2.add(jCheckBoxMenuItem3);

        jMenuItem7.setText("Command help (english only)");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Skin");

        mNimbus.setText("Nimbus");
        mNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNimbusActionPerformed(evt);
            }
        });
        jMenu3.add(mNimbus);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(lTopLeftCorner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lRenderWorld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lRenderType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jButton1)
                            .addComponent(checkBoxIncludeSkylight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lSingleplayerSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lCustomPath, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coordinateXmin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coordinateXmax, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lOutputFilename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboSelectWorld, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelectedWorldPath)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generateMapButton, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                            .addComponent(consolePanel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OutputFilename, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkBox64bit)
                            .addComponent(lOtherParams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lMemoryLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(memVal, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memLabel))
                            .addComponent(otherParameters)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboSelectWorld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectedWorldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOutputFilename)
                    .addComponent(OutputFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateMapButton)
                    .addComponent(newWindowButton)
                    .addComponent(lCustomPath)
                    .addComponent(lSingleplayerSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consolePanel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lTopLeftCorner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(lRenderWorld)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lRenderType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkBoxIncludeSkylight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(coordinateXmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coordinateXmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(checkBox64bit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOtherParams))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lMemoryLimit)
                        .addGap(29, 29, 29)
                        .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectWorld(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectWorld
        if (ComboSelectWorld.getSelectedIndex() == -1) return;
        String sep = System.getProperty("file.separator");
        if (System.getenv("APPDATA") != null)
            SelectedWorldPath.setText(System.getenv("APPDATA")+sep+".minecraft"+sep+"saves"+sep
                +ComboSelectWorld.getItemAt(ComboSelectWorld.getSelectedIndex()).toString());
        else
            SelectedWorldPath.setText(System.getProperty("user.home")+sep+".minecraft"+sep+"saves"+sep
                    +ComboSelectWorld.getItemAt(ComboSelectWorld.getSelectedIndex()).toString());
        changeOutputFileName();
    }//GEN-LAST:event_selectWorld

    private void generujSwiat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generujSwiat
        String direction="", renderWorld="", renderType="";
        
        switch (listTopLeftCorner.getSelectedIndex())
        {
            case 0:
                direction = " -east";
                break;
            case 1:
                direction = " -south";
                break;
            case 2:
                direction = " -west";
                break;
            case 3:
                direction = " -north";
                break;
        }
        switch (listRenderWorld.getSelectedIndex())
        {
            case 0:
                renderWorld = "";
                break;
            case 1:
                renderWorld = " -hell";
                break;
            case 2:
                renderWorld = " -end";
                break;
        }
        if (listRenderWorld.getSelectedIndex() == 0)
        switch (listRenderType.getSelectedIndex())
        {
            case 0:
                renderType = "";
                break;
            case 1:
                renderType = " -night";
                break;
            case 2:
                renderType = " -cave";
                break;
            case 3:
                renderType = " -blendcave";
                break;
        }
        
        String command = mcmapEXE+
                " \""+
                SelectedWorldPath.getText()+
                "\" -file \""+
                OutputFilename.getText()+
                "\" -mem "+
                new Integer((int)Math.pow(2,memVal.getValue()/(float)100))+
                direction+
                renderWorld+
                renderType+
                (checkBoxIncludeSkylight.isSelected() ? " -skylight" : "")+
                " "+
                otherParameters.getText();
        new RunMe(command,this).start();
        
        //TODO: breaking renderring
        
    }//GEN-LAST:event_generujSwiat

    private void zmianaLimituPamieci(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zmianaLimituPamieci
        Integer memlimit = new Integer((int)Math.pow(2,memVal.getValue()/(float)100));
        if (memlimit < 8192)
        memLabel.setText(memlimit.toString() + " MB");
        else
        memLabel.setText("<html><font color=red><b>" + memlimit.toString() + "&nbsp;MB</b></font></html>");
    }//GEN-LAST:event_zmianaLimituPamieci

    private void newWindowClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWindowClick
        new Window();
    }//GEN-LAST:event_newWindowClick

    private void goToSite(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToSite
        try{Desktop.getDesktop().browse(new URI("http://wrim.pl/mcmap"));}
        catch(IOException|URISyntaxException e){}
    }//GEN-LAST:event_goToSite

    private void changeLanguageEnglish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLanguageEnglish
        HashMap<String, String> map = new HashMap<>();
        map.put("lCustomPath", "Custom path");
        map.put("lMemoryLimit", "Memory limit (use carefuly)");
        map.put("lOtherParams", "Other params");
        map.put("lOutputFilename", "Output filename");
        map.put("lSingleplayerSave", "Singleplayer Save");
        map.put("lTitle", "<html><a style=\"text-decoration:none;cursor:pointer;\" href=\"http://wrim.pl/mcmap/\">Manually Check for updates</a></html>");
        map.put("mInformation", "About");
        map.put("lTopLeftCorner", "Top-left corner:");
        map.put("lRenderWorld", "Render World:");
        map.put("lRenderType", "Render type:");
        map.put("checkBox64bit", "64 bit version");
        map.put("IncludeSkylight", "Include skylight");
        map.put("mLanguage", "Language");
        map.put("version", "Verion: ");
        map.put("updateTo", "Update to: ");
        map.put("newWindowButton", "New window");
        map.put("generateMapButton", "Generate map");
        
        map.put("DirectionEast","East");
        map.put("DirectionSouth","South");
        map.put("DirectionWest","West");
        map.put("DirectionNorth","North");
        
        map.put("RenderWorldOverworld","Overworld");
        map.put("RenderWorldNether","Nether");
        map.put("RenderWorldEnd","End");
        
        map.put("RenderTypeDay","Day");
        map.put("RenderTypeNight","Night");
        map.put("RenderTypeUnderground","Underground");
        map.put("RenderTypeCaves","Overworld + caves");
        
        changeLanguage(map);
        mLangEnglish.setSelected(true);
    }//GEN-LAST:event_changeLanguageEnglish

    private void changeLanguagePolish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLanguagePolish
        HashMap<String, String> map = new HashMap<>();
        map.put("lCustomPath", "Własna ścieżka");
        map.put("lMemoryLimit", "Limit pamięci (używaj ostrożnie)");
        map.put("lOtherParams", "Inne parametry");
        map.put("lOutputFilename", "Nazwa obrazu");
        map.put("lSingleplayerSave", "Domyślna ścieżka");
        map.put("lTitle", "<html><a style=\"text-decoration:none;cursor:pointer;\" href=\"http://wrim.pl/mcmap/\">Ręcznie sprawdź dostępność aktualizacji</a></html>");
        map.put("lTopLeftCorner", "Lewy górny narożnik:");
        map.put("lRenderWorld", "Świat:");
        map.put("lRenderType", "Typ generowania:");
        map.put("checkBox64bit", "Wersja 64 bitowa");
        map.put("IncludeSkylight", "Uwzględniaj słońce");
        map.put("mInformation", "Informacje");
        map.put("mLanguage", "Język");
        map.put("version", "Wersja: ");
        map.put("updateTo", "Aktualizuj do ");
        map.put("newWindowButton", "Nowe okno");
        map.put("generateMapButton", "Generuj obraz mapy");
        
        map.put("DirectionEast","Wschód");
        map.put("DirectionSouth","Południe");
        map.put("DirectionWest","Zachód");
        map.put("DirectionNorth","Północ");
        
        map.put("RenderWorldOverworld","Zwykły świat");
        map.put("RenderWorldNether","Nether");
        map.put("RenderWorldEnd","End");
        
        map.put("RenderTypeDay","Dzień");
        map.put("RenderTypeNight","Noc");
        map.put("RenderTypeUnderground","Podziemia");
        map.put("RenderTypeCaves","Zwykły świat + jaskinie");
        
        changeLanguage(map);
        mLangPolish.setSelected(true);
        
        JRadioButtonMenuItem newrb = new javax.swing.JRadioButtonMenuItem();

        newrb.setText("English (non-default)");
        newrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLanguageEnglish(evt);
            }
        });
        mLanguage.add(newrb);
        mLanguage.remove(0);

        
    }//GEN-LAST:event_changeLanguagePolish

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void changeVersion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeVersion
        if (checkBox64bit.isSelected())
        {
            mcmapEXE = "mcmap64.exe";
            memVal.setMaximum(1400);
        }
        else
        {
            mcmapEXE = "mcmap.exe";
            memVal.setMaximum(1159);
        }
    }//GEN-LAST:event_changeVersion

    private void listTopLeftCornerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTopLeftCornerValueChanged
        changeOutputFileName();
    }//GEN-LAST:event_listTopLeftCornerValueChanged

    private void listRenderWorldValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRenderWorldValueChanged
        changeOutputFileName();
    }//GEN-LAST:event_listRenderWorldValueChanged

    private void listRenderTypeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRenderTypeValueChanged
        changeOutputFileName();
    }//GEN-LAST:event_listRenderTypeValueChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        /*
        String[] items = {"One", "Two", "Three", "Four", "Five"};
        JComboBox combo = new JComboBox(items);
        JTextField field1 = new JTextField("1234.56");
        JTextField field2 = new JTextField("9876.54");
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(combo);
        panel.add(new JLabel("Field 1:"));
        panel.add(field1);
        panel.add(new JLabel("Field 2:"));
        panel.add(field2);
        int result = JOptionPane.showConfirmDialog(null, panel, "Test",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(combo.getSelectedItem()
                + " " + field1.getText()
                + " " + field2.getText());
        } else {
            System.out.println("Cancelled");
        }
        */
        
        new Bounds().main(new String[]{});
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void coordinateXmaxcoordinateXminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coordinateXmaxcoordinateXminFocusLost
        Long num;

        num = new Long(coordinateXmin.getText());
        num = (long)Math.floor((double)num/16)*16;
        coordinateXmin.setText(num.toString());

        num = new Long(coordinateXmax.getText());
        if (num % 16 == 0)
        num = (long)Math.ceil((double)num/16)*16 + 15;
        else
        num = (long)Math.ceil((double)num/16)*16 - 1;
        coordinateXmax.setText(num.toString());
    }//GEN-LAST:event_coordinateXmaxcoordinateXminFocusLost

    private void coordinateXminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coordinateXminFocusLost
        Long num;

        num = new Long(coordinateXmin.getText());
        num = (long)Math.floor((double)num/16)*16;
        coordinateXmin.setText(num.toString());

        num = new Long(coordinateXmax.getText());
        if (num % 16 == 0)
        num = (long)Math.ceil((double)num/16)*16 + 15;
        else
        num = (long)Math.ceil((double)num/16)*16 - 1;
        coordinateXmax.setText(num.toString());
    }//GEN-LAST:event_coordinateXminFocusLost

    private void mNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNimbusActionPerformed
        try {
                //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                UIManager.setLookAndFeel(new com.jtattoo.plaf.aero.AeroLookAndFeel());
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(this, e.toString(), "Błąd", JOptionPane.ERROR_MESSAGE);
                }
                SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_mNimbusActionPerformed

        private static void display() {
        String[] items = {"One", "Two", "Three", "Four", "Five"};
        JComboBox combo = new JComboBox(items);
        JTextField field1 = new JTextField("1234.56");
        JTextField field2 = new JTextField("9876.54");
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(combo);
        panel.add(new JLabel("Field 1:"));
        panel.add(field1);
        panel.add(new JLabel("Field 2:"));
        panel.add(field2);
        int result = JOptionPane.showConfirmDialog(null, panel, "Test",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println(combo.getSelectedItem()
                + " " + field1.getText()
                + " " + field2.getText());
        } else {
            System.out.println("Cancelled");
        }
    }
        
    private void changeOutputFileName() {                                      
        if (ComboSelectWorld.getSelectedIndex() == -1) return;
        
        String fileName = "";
        switch (listTopLeftCorner.getSelectedIndex())
        {
            case 0:
                fileName += "East-";
                break;
            case 1:
                fileName += "South-";
                break;
            case 2:
                fileName += "West-";
                break;
            case 3:
                fileName += "North-";
                break;
        }
        fileName += ComboSelectWorld.getItemAt(ComboSelectWorld.getSelectedIndex()).toString();
        switch (listRenderWorld.getSelectedIndex())
        {
            case 0:
                fileName += "";
                break;
            case 1:
                fileName += "_Nether";
                break;
            case 2:
                fileName += "_End";
                break;
        }
        if (listRenderWorld.getSelectedIndex() == 0)
        switch (listRenderType.getSelectedIndex())
        {
            case 0:
                fileName += "";
                break;
            case 1:
                fileName += "_Night";
                break;
            case 2:
                fileName += "_Underground";
                break;
            case 3:
                fileName += "_Blendcaves";
                break;
        }
        
        OutputFilename.setText(fileName+".png");
    }                                     

    private void changeLanguage(HashMap<String, String> map)
    {
        //setLanguageElement(lCustomPath, "lCustomPath", map);
        lCustomPath.setText(map.get("lCustomPath"));
        lMemoryLimit.setText(map.get("lMemoryLimit"));
        lOtherParams.setText(map.get("lOtherParams"));
        lOutputFilename.setText(map.get("lOutputFilename"));
        lSingleplayerSave.setText(map.get("lSingleplayerSave"));
        lTitle.setText(map.get("lTitle"));
        lTopLeftCorner.setText(map.get("lTopLeftCorner"));
        lRenderWorld.setText(map.get("lRenderWorld"));
        lRenderType.setText(map.get("lRenderType"));
        checkBox64bit.setText(map.get("checkBox64bit"));
        checkBoxIncludeSkylight.setText(map.get("IncludeSkylight"));
        mInformation.setText(map.get("mInformation"));
        mLanguage.setText(map.get("mLanguage"));
        newWindowButton.setText(map.get("newWindowButton"));
        generateMapButton.setText(map.get("generateMapButton"));
        
        mVersion.setText(map.get("version") + "N/A");
        mUpdate.setText(map.get("updateTo") + "2.4.2d");
        
        DefaultListModel model;
        int selected;
        
        selected = listTopLeftCorner.getSelectedIndex();
        model = new DefaultListModel();
        model.addElement(map.get("DirectionEast"));
        model.addElement(map.get("DirectionSouth"));
        model.addElement(map.get("DirectionWest"));
        model.addElement(map.get("DirectionNorth"));
        listTopLeftCorner.setModel(model);
        listTopLeftCorner.setSelectedIndex(selected);
        
        selected = listRenderWorld.getSelectedIndex();
        model = new DefaultListModel();
        model.addElement(map.get("RenderWorldOverworld"));
        model.addElement(map.get("RenderWorldNether"));
        model.addElement(map.get("RenderWorldEnd"));
        listRenderWorld.setModel(model);
        listRenderWorld.setSelectedIndex(selected);
        
        selected = listRenderType.getSelectedIndex();
        model = new DefaultListModel();
        model.addElement(map.get("RenderTypeDay"));
        model.addElement(map.get("RenderTypeNight"));
        model.addElement(map.get("RenderTypeUnderground"));
        model.addElement(map.get("RenderTypeCaves"));
        listRenderType.setModel(model);
        listRenderType.setSelectedIndex(selected);
        
        mLangEnglish.setSelected(false);
        mLangPolish.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        System.out.println(UIManager.getSystemLookAndFeelClassName());
        
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                System.out.println(info.getName());
            }

        
        try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
            }
            }
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//            UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel");
//            UIManager.setLookAndFeel(new com.jtattoo.plaf.fast.FastLookAndFeel());
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        if (args.length == 1 && args[0].equals("Constructor"))  //TODO cleanup that mess
            return;
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
 
            }
        });

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboSelectWorld;
    private javax.swing.JTextField OutputFilename;
    private javax.swing.JTextField SelectedWorldPath;
    private javax.swing.JCheckBox checkBox64bit;
    private javax.swing.JCheckBox checkBoxIncludeSkylight;
    javax.swing.JList consoleList;
    private javax.swing.JScrollPane consolePanel;
    private javax.swing.JFormattedTextField coordinateXmax;
    private javax.swing.JTextField coordinateXmin;
    javax.swing.JButton generateMapButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    javax.swing.JProgressBar jProgressBar1;
    javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JRadioButton lCustomPath;
    private javax.swing.JLabel lMemoryLimit;
    private javax.swing.JLabel lOtherParams;
    private javax.swing.JLabel lOutputFilename;
    private javax.swing.JLabel lRenderType;
    private javax.swing.JLabel lRenderWorld;
    private javax.swing.JRadioButton lSingleplayerSave;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lTopLeftCorner;
    private javax.swing.JList listRenderType;
    private javax.swing.JList listRenderWorld;
    private javax.swing.JList listTopLeftCorner;
    private javax.swing.JMenu mInformation;
    private javax.swing.JRadioButtonMenuItem mLangEnglish;
    private javax.swing.JRadioButtonMenuItem mLangPolish;
    private javax.swing.JMenu mLanguage;
    private javax.swing.JRadioButtonMenuItem mNimbus;
    private javax.swing.JMenuItem mUpdate;
    private javax.swing.JMenuItem mVersion;
    private javax.swing.JLabel memLabel;
    private javax.swing.JSlider memVal;
    javax.swing.JButton newWindowButton;
    private javax.swing.JTextField otherParameters;
    // End of variables declaration//GEN-END:variables

}
